Implement calculations in periodic boundary conditions
deepmind/ferminet pull request #49
Opened 2022-06-29 12:07 UTC by gcassella

Includes the feature layer, envelope, and Hamiltonian described in
```
Cassella, G., Sutterud, H., Azadi, S., Drummond, N.D., Pfau, D.,
Spencer, J.S. and Foulkes, W.M.C., 2022. Discovering Quantum Phase Transitions
with Fermionic Neural Networks. arXiv preprint arXiv:2202.05183.
```

Several changes to the configuration interface for feature layers and envelopes have been made. These are now specified by an interface similar to the local energy function. These changes, and the new periodic boundary conditions, are demonstrated in `ferminet.configs.heg`.

Other miscellaneous changes:
- Reduced failure threshold for the `pylint` step of the GitHub CI workflow to `9.75/10.0`. This prevents the CI from failing over linting errors that are acceptable under the in-house style.
- Implemented dummy element 'X' with atomic number zero. Used to define the coordinate system for one-electron features in systems without nuclei (e.g. the homogeneous electron gas).

2022-06-30 15:46 UTC, jsspencer approved these changes
This is awesome, thank you!

2022-07-01 10:21 UTC, jsspencer requested changes

2022-07-01 10:21 UTC, jsspencer commented on ferminet/pbc/hamiltonian.py
> +  lat_vec_norm = jnp.linalg.norm(lat_vectors[1:], axis=-1)
Would be more readable if you moved this above `real_sum` so all "top-level" code is grouped together, before the internal functions which close over the variables here.

2022-07-01 10:21 UTC, jsspencer commented on ferminet/pbc/hamiltonian.py
> +  def real_sum(separation: jnp.ndarray):
A little more verbose name here

real_space_ewald? (similarly for recp_sum)

2022-07-01 15:11 UTC, gcassella commented on ferminet/train.py
> -    make_local_energy = getattr(local_energy_module, local_energy_fn)  # type: hamiltonian.MakeLocalEnergy
This is actually correct - the previous version was wrong! Pytype agrees.

2022-07-04 10:01 UTC, gcassella commented
I think that addresses all of the comments - thank you for taking the time to go through everything and make clear recommendations :smile:

2022-07-04 10:02 UTC, jsspencer approved these changes

2022-07-12 19:23 UTC, merged